server {
    if ($host = xxx.nagiyu.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name xxx.nagiyu.com;
    return 404; # managed by Certbot
}

server {
    server_name xxx.nagiyu.com;

    resolver 8.8.8.8 ipv6=off valid=10s;
    set $lambda_upstream "xxxxxxxxxx.lambda-url.ap-northeast-3.on.aws";

    location / {
        proxy_pass https://$lambda_upstream;
        proxy_set_header Host xxxxxxxxxx.lambda-url.ap-northeast-3.on.aws;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # TODO: 暫定追加なので不要かも
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        # TODO: 暫定追加なので不要かも
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        send_timeout 60s;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/xxx.nagiyu.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/xxx.nagiyu.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
